apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth
  name: auth
spec:
  ports:
  - name: "3002"
    port: 3002
    protocol: TCP
    targetPort: 3002
  - name: "3003"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: auth
  type: ClusterIP
status:
  loadBalancer: {}
